### ISSUE TITLE
Unable to download packs

### ISSUE THREAD

**Issue by Roadcrosser** [portablejim/curseDownloader#1]
I did a test to try downloading both FTB Infinity and Magic Farm 3.

I unzipped them to the desktop and pointed the program at the json, but all I got was 
![image](https://cloud.githubusercontent.com/assets/7963090/7105047/b666c26c-e137-11e4-8e8e-a4f3b59f53b9.png) from MF3 and 
![image](https://cloud.githubusercontent.com/assets/7963090/7105048/bfa7e7c0-e137-11e4-9bef-b4c44599df45.png) from FTB Infinity.

Any ideas?

**Comment by portablejim** [comment]
MF3: What folder was the program in? And what folder was the modpack json in?

Infinity: There is actually invalid json in the infinity download. I'll make a patch to fix it.
