### ISSUE TITLE
mods folder not created automatically

### ISSUE THREAD

**Issue by wshadow** [portablejim/curseDownloader#17]
I used the version from #6 to avoid the issue described in #5. The download failed, because the mods folder didn't exist yet and the downloaded mod could therefore not be saved there. Manually adding the folder at the correct location solved the issue.

> ./downloader.py --manifest ./NFINIT/manifest.json --nogui
> 137 files to download
> [1/137] ActuallyAdditions-1.8.9-r26.jar
> Traceback (most recent call last):
>   File "./downloader.py", line 192, in <module>
>     doDownload(args.manifest)
>   File "./downloader.py", line 148, in doDownload
>     with open(mod_filename, "wb") as mod:
> FileNotFoundError: [Errno 2] No such file or directory: 'NFINIT/minecraft/mods/ActuallyAdditions-1.8.9-r26.jar'

**Comment by iarspider** [comment]
I believe this happens if "minecraft" folder exists, but "minecraft/mods" doesn't.

**Comment by TOLoneWolf** [comment]
yeah looks like making a mods folder got  put inside the code that makes the minecraft folder, so if it doesn't need to make a minecraft folder it skips that line as well.
https://github.com/portablejim/curseDownloader/blob/master/downloader.py#L119-L121
