### ISSUE TITLE
What exactly am I supposed to do here?

### ISSUE THREAD

**Issue by Orgnolf** [portablejim/curseDownloader#18]
Step 3: 

Run

python3.4 /path/to/downloader.py /path/to/manifest.json

**Comment by tkdberger** [comment]
Open a terminal and type that command.

For instance, let's assume you have the downloader script (and all the other files in this repository) in `~` (the Linux home directory) and `manifest.json` in `~/Downloads` (the default location for downloaded files.)
If you're on Windows, the paths probably look something like `C:\Users\YourUserName\` and `C:\Users\YourUserName\Downloads`
Once you've made sure you know the locations of those files, open a terminal and type `python`.

The output should look something like this:
```
Python 2.7.11+ (default, Apr 17 2016, 14:00:29) 
[GCC 5.3.1 20160413] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>
``` 
Go ahead and type `exit()` to exit the python interpreter.
(If you get an error saying the command wasn't recognized, you need to get Python from [their website.](https://www.python.org))
On line one, you can see your Python version. Make sure it's 3.4 or above. In my case, it's not so I have to use the command `python3`.

Once you've affirmed your python version is correct, type your final command as follows:
```
python [Where downloader.py is] [Where manifest.json is]
```
OR if the first command fails to do it:
```
python3 [Where downloader.py is] [Where manifest.json is]
```
Of course, substitute in the actual paths and drop the brackets.

**Comment by Orgnolf** [comment]
I'm running Windows 7, should have mentioned that earlier, I guess.
I don't know what a "terminal" is.
Do you mean cmd.exe? I've typed `python`, but it doesn't recognize the command.

**Comment by tkdberger** [comment]
>I don't know what a "terminal" is.

Under Windows, yeah that's cmd.exe or the Command Prompt as Windows officially calls it.
Look in the start menu, is there anything in a folder labeled 'Python' (or similar)? Should have items like IDLE, among others that I can't remember off the top of my head.

**Comment by Orgnolf** [comment]
I have these: [http://puu.sh/p8aD6/1aa4303401.png](url)

**Comment by tkdberger** [comment]
Alright, so it looks like you did install Python successfully.

Please open 'Python (command line)' and post results.

**Comment by Orgnolf** [comment]
This is what it says when opened:

`Python 3.4.0 <v3.4.0:04f714765c13, Mar 16 2014, 19:25:23> 
[MSC v.1600 64 bit <AMD64>] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>`

Then, typing `python` followed by both paths yields the following: 
`File "<stdin>", line 1
python [path to downloader.py] [path to manifest.json]
^
SyntaxError: invalid syntax
>>>`

**Comment by tkdberger** [comment]
Okay, so Python is installed and working.
Try running `python3` in a command prompt, and let me know what happens.

**Comment by Orgnolf** [comment]
cmd: 
same output as `python`

python command line:
`Traceback <most recent call last>:`
`  File "<stdin>", line 1, in <module>`
`NameError: name'python3' is not defined`
`>>>`

**Comment by tkdberger** [comment]
No, I mean open a new Windows command line and try to run `python3`. Should've made that clearer, sorry.

**Comment by Orgnolf** [comment]
Please explain like I'm five.
Am I supposed to install python 3.0?

**Comment by tkdberger** [comment]
Hmm, alright.If you have Python 3.4 or greater installed correctly, running `python` or `python3` should bring up the Python interpreter. 

The latest and greatest version can be found [here.](https://www.python.org/downloads/release/python-351/)
Once you've made sure that's installed, and you can get `python` or `python3` to work right, you should them be able to type `python [path to downloader.py] [path to manifest.json]` or `python3 [path to downloader.py] [path to manifest.json]` and get the script to run.
If for some reason using the Python installer doesn't get you to at least calling the interpreter from cmd, I really can't help you. I'm too used  to it being built in (Ubuntu comes with Python).

**Comment by Orgnolf** [comment]
3.5 does not work either.
At least you tried, thank you for that.
