### ISSUE TITLE
Doesn't create dirs automatically.

### ISSUE THREAD

**Issue by luckcolors** [portablejim/curseDownloader#3]
_From @luckcolors on April 25, 2015 14:59_

Hello.
I've got an suggestion and a bug to report :).
1. Please add the info about installing dependency "appdirs" and "requests" need to run this python script
2. Make the python script able to create a folder if needed like: The program needs to download a file in C:\modpack\mods\file..... if the folder mods is missing the program will return error.
3 Also could you make the cache portable? I mean stored in the folder of the python script?

_Copied from original issue: portablejim/Jims-Mod-Manager#1_

**Comment by luckcolors** [comment]
_From @portablejim on April 25, 2015 16:0_

Is this in the wrong project? This one is a java based thing.
You may have wanted https://github.com/portablejim/curseDownloader

**Comment by luckcolors** [comment]
yeah sorry....

**Comment by portablejim** [comment]
Installing `appdirs` and `requests` is done by

    pip3 install appdirs requests

I have fixed the mod-folder creation problem.

Making the cache portable definitely is a possibility.

**Comment by luckcolors** [comment]
Thanks :).
