### ISSUE TITLE
Fails to download new packs because curse url moved

### ISSUE THREAD

**Issue by shortcarver** [portablejim/curseDownloader#35]
The app fails to download new packs because curse url moved. I've created a fix, but I can't make a PR.

Just open downloader.py and change the sess.get() cal to look like this:

>         # File is not cached and needs to be downloaded
>         projectResponse = sess.get("https://minecraft.curseforge.com/projects/%s" % (dependency['projectID']), stream=True)
>         fileResponse = sess.get("%s/files/%s/download" % (projectResponse.url, dependency['fileID']), stream=True)

**Comment by HugoPoi** [comment]
Resolve by https://github.com/portablejim/curseDownloader/pull/37
