### ISSUE TITLE
Curse Import

### ISSUE THREAD

**Issue by gazpachoking** [portablejim/curseDownloader#7]
This might be out of scope for this project, but it would be cool if we could figure out what we needed in minecraftinstance.json to be able to import a modpack into curse launcher. I was looking for a good way to distribute a custom modpack to my friends for my server, and thought curse launcher would be great when I saw the export feature... until I realized there is no import one.

**Comment by TOLoneWolf** [comment]
I don't know if they added this or if was there the whole time but on the curse launcher there is an import button. Create custom profile -> button text that says import

**Comment by gazpachoking** [comment]
Yeah, they must have added that at some point. Or I was totally blind when I created the issue. :stuck_out_tongue:
